// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdhYDpwrNc3LFMM8EU87CfyAvfNC5Bz7Y',
    appId: '1:383150658238:web:3e9808018268a1b8bc44ef',
    messagingSenderId: '383150658238',
    projectId: 'race-tracker-project',
    authDomain: 'race-tracker-project.firebaseapp.com',
    storageBucket: 'race-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUq_PDQA_6telKZTQ2tA6UyB3TIoCp5c8',
    appId: '1:383150658238:android:03d655ee287a88ecbc44ef',
    messagingSenderId: '383150658238',
    projectId: 'race-tracker-project',
    storageBucket: 'race-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdhYDpwrNc3LFMM8EU87CfyAvfNC5Bz7Y',
    appId: '1:383150658238:web:c41ee9fba0a5f277bc44ef',
    messagingSenderId: '383150658238',
    projectId: 'race-tracker-project',
    authDomain: 'race-tracker-project.firebaseapp.com',
    storageBucket: 'race-tracker-project.firebasestorage.app',
  );
}
